name: Webhook Disptacher Deploy
on:
  workflow_dispatch:
    inputs:
      client:
        description: 'client name, for all use: All'
        required: true
        default: 'All'
      stage:
        description: 'stage i.e. staging or prod only '
        required: true
        default: 'prod'
      project:
        description: 'Project or microservice name'
        required: true
        default: 'webhook_dispatcher'

jobs:
  deployment:

    env:
      project: ${{ github.event.inputs.project }}
      stage: ${{ github.event.inputs.stage }}
      client: ${{ github.event.inputs.client }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: kuldeep-test/test-composite
          token: ${{ secrets.GH_TOKEN }}
          path: .github/actions/custom-action

      - name: 'Perform common steps'
        uses: ./.github/actions/custom-action
        id: custom-action
        with:
          stage: "prod"
          client: "All"
